services:
  llm-microservice:
    image: ghcr.io/alexbomber12/llm_microservice:${LLM_TAG:-v1.2.1}
    runtime: nvidia
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME          # pulled from .env
      - GPU_MEMORY_UTILIZATION
      - HF_HOME
      - LLM_API_KEY         # may be empty
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/llm_models:/models
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
