site_name: LLM Microservice
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - SDK: sdk.md
  - Architecture: architecture.md
  - ADRs:
      - ADR 0001: adr/0001-record-architecture.md
docs_dir: docs
