name: Publish Docker image to GHCR

on:
  push:
    tags: ["v*"]               # e.g. v1.1.0, v2.0.1

jobs:
  push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write          # allow pushing to GHCR
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/alexbomber12/llm_microservice:${{ github.ref_name }}
          provenance: false      # disable SBOM for faster push (enable later if needed)
